spring:
  application:
    name: microservice-consumer-movice
server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.itmuch.cloud.feign.UserFeignClient: DEBUG
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.command.default.execution.timeout.enable: false
feign.hystrix.enable: false