spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing
server:
  port: 8010
eureka:
  client:
    region:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule