spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix-propagation
server:
  port: 8010
management:
  security:
    enabled: false #关掉安全认证
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000